## Preprocessing

In [97]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [98]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ["EIN", "NAME"])

In [99]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [100]:
# Look at APPLICATION_TYPE value counts for binning
print( application_df["APPLICATION_TYPE"].value_counts() )

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [101]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = []
num = application_df["APPLICATION_TYPE"].unique()
cutoffVal = 500

for i in range(0, len(num)):
  if application_df["APPLICATION_TYPE"].value_counts()[num[i]] <= cutoffVal:
    application_types_to_replace.append(num[i])


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [102]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [103]:
# You may find it helpful to look at CLASSIFICATION value counts >1
app_df = application_df

##bins = [0, 1, 20000]
##labels = [0, 'low', '']

app_df.groupby("CLASSIFICATION").filter(lambda x: len(x) > 1)["CLASSIFICATION"].value_counts()


##app_df.head()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C4100        6
C1720        6
C2400        6
C1600        5
C1257        5
C1260        3
C2710        3
C0           3
C1267        2
C1256        2
C1234        2
C1246        2
C3200        2
Name: CLASSIFICATION, dtype: int64

In [104]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = []
num = application_df["CLASSIFICATION"].unique()
cutoffVal = 1000

for i in range(0, len(num)):
  if application_df["CLASSIFICATION"].value_counts()[num[i]] <= cutoffVal:
    classifications_to_replace.append(num[i])

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [105]:
# Convert categorical data to numeric with `pd.get_dummies`

application_df["SPECIAL_CONSIDERATIONS"] = pd.get_dummies(application_df["SPECIAL_CONSIDERATIONS"], drop_first=True, dtype='int')

USE_CASE = pd.get_dummies(application_df["USE_CASE"], dtype='int')
CLASSIFICATION = pd.get_dummies(application_df["CLASSIFICATION"], dtype='int')
APPLICATION_TYPE = pd.get_dummies(application_df["APPLICATION_TYPE"], dtype='int')
ORGANIZATION = pd.get_dummies(application_df["ORGANIZATION"], dtype='int')
AFFILIATION = pd.get_dummies(application_df["AFFILIATION"], dtype='int')
INCOME_AMT = pd.get_dummies(application_df["INCOME_AMT"], dtype='int')


application_df = application_df.merge(USE_CASE,left_index=True, right_index=True)
application_df = application_df.merge(CLASSIFICATION,left_index=True, right_index=True)
application_df = application_df.merge(APPLICATION_TYPE,left_index=True, right_index=True)
application_df = application_df.merge(ORGANIZATION,left_index=True, right_index=True)
application_df = application_df.merge(AFFILIATION,left_index=True, right_index=True)
application_df = application_df.merge(INCOME_AMT,left_index=True, right_index=True)


application_df = application_df.drop(columns=["USE_CASE", "CLASSIFICATION", "APPLICATION_TYPE", "ORGANIZATION", "AFFILIATION", "INCOME_AMT"])

application_df.head()

<ipython-input-105-24d76c9302d3>:17: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Other_x'} in the result is deprecated and will raise a MergeError in a future version.
  application_df = application_df.merge(AFFILIATION,left_index=True, right_index=True)

,STATUS,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,CommunityServ,Heathcare,Other_x,Preservation,ProductDev,C1000,...,Regional,0,1-9999,10000-24999,100000-499999,10M-50M,1M-5M,25000-99999,50M+,5M-10M
0,1,0,5000,1,0,0,0,0,1,1,...,0,1,0,0,0,0,0,0,0,0
1,1,0,108590,1,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,0,5000,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
3,1,0,6692,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1,0,142590,1,0,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0

In [106]:
import matplotlib.pyplot as plt

# Split our preprocessed data into our features and target arrays
y = application_df.IS_SUCCESSFUL.values
X = application_df.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [107]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [108]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  64
hidden_nodes_layer2 = 32
hidden_nodes_layer3 = 16
hidden_nodes_layer4 = 8
hidden_nodes_layer5 = 4
hidden_nodes_layer6 = 2


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation="relu", input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))

# Fifth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer5, activation="relu"))

# Sixth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer6, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_64 (Dense)            (None, 64)                2752

 dense_65 (Dense)            (None, 32)                2080

 dense_66 (Dense)            (None, 16)                528

 dense_67 (Dense)            (None, 8)                 136

 dense_68 (Dense)            (None, 4)                 36

 dense_69 (Dense)            (None, 2)                 10

 dense_70 (Dense)            (None, 1)                 3

=================================================================
Total params: 5545 (21.66 KB)
Trainable params: 5545 (21.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [109]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [110]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 3ms/step - loss: 0.5771 - accuracy: 0.7190
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5556 - accuracy: 0.7304
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5524 - accuracy: 0.7318
Epoch 4/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5511 - accuracy: 0.7324
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7335
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7338
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7338
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7332
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7349
Epoch 10/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5469 - accuracy: 0.7348
Epoch 11/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5462 - accuracy: 0.7349
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7353
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7356
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7358
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7366
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7366
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5441 - accuracy: 0.7356
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7370
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7376
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7378
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7385
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7365
Epoch 23/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5422 - accuracy: 0.7382
Epoch 24/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5415 - accuracy: 0.7388
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7379
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7381
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7381
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7382
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7384
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5403 - accuracy: 0.7360
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7371
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7368
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7375
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7383
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7377
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7388
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5396 - accuracy: 0.7385
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7378
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7387
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7395
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7378
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7391
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7388
Epoch 44/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5393 - accuracy: 0.7390
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7389
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7390
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7394
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7386
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7386
Epoch 50/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7391

In [113]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5527 - accuracy: 0.7259 - 783ms/epoch - 3ms/step
Loss: 0.5526526570320129, Accuracy: 0.7259474992752075

In [114]:
# Export our model to HDF5 file

fit_model.save_weights('my_model.hdf5')

AttributeError: ignored